version: '3'
services:
  etcd:
    container_name: etcd
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3
    ports:
      - 2379:2379
      - 2380:2380
  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  traefik:
    container_name: traefik
    image: traefik
    command:
      - "--configFile=/etc/traefik/config.yaml"
    volumes:
      - "./traefik:/etc/traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
