debug: true
discovery:
  etcdComponentName: 'etcd'

node:
  api:
    portRange:
      - 9000
      - 9010
    host: '<host>'

services:
  http-gateway:
    httpListener:
      portRange:
        - 9000
        - 9010
      host: '<host>'
    traefik:
      prefix: traefik

  restful:
    tcpListener:
      portRange:
        - 9000
        - 9010
      host: '<host>'

components:
  account-redis:
    host: <host>
    port: <port>
    db: <db>
    prefix: 'test'
  account-database:
    database:
      type: 'mysql'
      host: <host>
      port: <port>
      username: root
      password: root
      database: test
  etcd:
    etcd:
      hosts:
      - '<etcd host>'
    ttl: 60
    prefix: 'test'

workers:
  database-migrate:
    components:
        - account-database
