debug: true
discovery:
  etcdComponentName: 'etcd'
  scope: '<scope>'

logger:
  file:
    fileFormat: '[./logs/server-]YYYY-MM-DD[.log]'

node:
  api:
    portRange:
      - 9000
      - 9010
    host: '<host>'

services:
  http-gateway:
    httpListener:
      portRange:
        - 9000
        - 9010
      host: '<host>'
    traefik:
      prefix: traefik
    websocketListener:
      portRange:
        - 7080
        - 7090
      host: '<host>'
      entryPath: '/ws'

  restful:
    tcpListener:
      portRange:
        - 9000
        - 9010
      host: '<host>'

  auth:
    tcpListener:
      portRange:
        - 9030
        - 9040
      host: '<host>'

components:
  business-redis:
    host: <host>
    port: <port>
    db: <db>
    prefix: <prefix>
  business-database:
    database:
      type: 'mysql'
      host: <host>
      port: <port>
      username: <username>
      password: <password>
      database: <database>
  etcd:
    etcd:
      hosts:
      - '<host>'
    ttl: 60
    prefix: <prefix>

workers:
  database-migrate:
    components:
        - business-database
